install: make 
language: cpp
dist: 
    - precise
    - trusty
    - xenial
os: ubuntu
compiler: gcc
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-all-dev
script: make debug; make release
notifications:
    email:
        recipients: aijunbai@gmail.com
        on_success: change
        on_failure: always

