install: make 
language: cpp
dist: 
    - precise
    - trusty
    - xenial
os: ubuntu
compiler: gcc
script: make debug; make release
notifications:
    email:
        recipients: aijunbai@gmail.com
        on_success: change
        on_failure: always

